name: PitchBlack CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v1
    - name: Initialize the Droid Builder
      uses: rokibhasansagar/actions_droid-builder@master
