name: PitchBlack CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v1
    - name: Initialize the Droid Builder
      uses: rokibhasansagar/actions_droid-builder@master
      with:
        args: '"
          cd $HOME/builder;
          git config --global user.email "rokibhasansagar2014@outlook.com";
          git config --global user.name "rokibhasansagar";
          git config --global color.ui true;
          git clone -q "https://${GITHUB_TOKEN}@github.com/rokibhasansagar/google-git-cookies.git" &> /dev/null;
          bash google-git-cookies/setup_cookies.sh && rm -rf google-git-cookies;
          mkdir $(pwd)/pbrp && cd pbrp/;
          repo init -q -u https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b "twrp-6.0" --depth 1;
          time repo sync -c -q --force-sync --no-clone-bundle --no-tags -j32;
          rm -rf device/qcom/ && rm -rf hardware/qcom/ && rm -rf device/generic/;
          git clone https://github.com/PitchBlackRecoveryProject/android_device_WALTON_Primo_RX5 device/WALTON/Primo_RX5;
          export ALLOW_MISSING_DEPENDENCIES=true;
          source build/envsetup.sh;
          lunch omni_Primo_RX5-userdebug;
          make -j$(nproc --all) recoveryimage;
          ghr -t ${GITHUB_TOKEN} -n "Test Release for Primo_RX5" -b "PBRP v2.9.0" -delete test out/target/product/Primo_RX5/PitchBlack*.zip
          "'
