name: PitchBlack CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1.2.0
    - name: Initialize the Droid Builder
      uses: rokibhasansagar/actions_droid-builder@master
      env:
        GitAllOAuth: ${{ secrets.GitAllOAuth }}
